### ISSUE TITLE
No installation notes provided

### ISSUE THREAD

**Issue by fdmatoz** [simunova/mtl4#1]
This package doesn't contain installation notes. The installation txt provide an URL which doesn't exist. 
![Screenshot from 2020-04-17 07-34-43](https://user-images.githubusercontent.com/12948049/79569818-fbae6880-807d-11ea-8224-54418a69cf96.png)

**Comment by Ravenwater** [comment]
@fdmatoz thanks for pointing out the orphaned link: 

The correct links are here:
https://www.simunova.com/en/mtl4/
http://old.simunova.com/mtl4

Installation is as simple as adding the root of where you cloned this repo to your compiler -I flag. If you use CMake then the MTLCmake.config is all you need to include in your CMAKE path.

Examples of how to integrate this MTL4 can be found at https://github.com/stillwater-sc/hpr-blas
